### ISSUE TITLE
RequestAbortedError [AbortError]: Request aborted

### ISSUE THREAD

**Issue by Yana5417** [hmes98318/ChatGPT-Discord-Bot#3]
login的时候，一直出现下面的错误请问怎么处理呢？

RequestAbortedError [AbortError]: Request aborted
    at abort (/Users/yananli/Desktop/works/discord-demos/ChatGPT-Discord-Bot-1.3.0/node_modules/undici/lib/api/abort-signal.js:10:18)
    at self.<computed> (/Users/yananli/Desktop/works/discord-demos/ChatGPT-Discord-Bot-1.3.0/node_modules/undici/lib/api/abort-signal.js:29:5)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)
    at EventTarget.dispatchEvent (node:internal/event_target:683:26)
    at abortSignal (node:internal/abort_controller:368:10)
    at AbortController.abort (node:internal/abort_controller:402:5)
    at Timeout.<anonymous> (/Users/yananli/Desktop/works/discord-demos/ChatGPT-Discord-Bot-1.3.0/node_modules/@discordjs/rest/dist/index.js:589:71)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'UND_ERR_ABORTED'
}

**Comment by hmes98318** [comment]
連線超時了，換個加速器試試。

**Comment by Yana5417** [comment]
> 連線超時了，換個加速器試試。

已解决（换了加速器）
